services:

  appDb:
    image: bitnami/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: capstoneproject
    ports: 
      - 3306:3306
    volumes:
      # - './data:/bitnami/mysql/data'
      - './initdb:/docker-entrypoint-initdb.d'
      - 'mysql_data:/bitnami/mysql/data'
    healthcheck:
      test: ["CMD", "mysql", "-u", "root",  "-ptoor", "-e", "show schemas"]
      interval: 10s 

  app:
    build: .
    restart: always
    depends_on:
      appDb:
        condition: service_healthy
    environment:
      HTTP_PORT: 8080
      STORAGE: db
    ports:
      - 80:8080

volumes:
  mysql_data:
    driver: local